remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [ACEMFS FUTMinna Bioinformatics Workshop]
description: [Course manual site for the 2025 ACEMFS FUTMinna Bioinformatics Workshop]
markdown: GFM
highlighter: rouge
